CREATE DATABASE NBA;

USE NBA;                       -- USING NBA'S 2023-2024 SEASON'S DATASET
SELECT * FROM player_stats;    -- DISPLAYING THE IMPORTED DATASET

-- DATASET ANALYSIS;

-- 1) AGE ANALYSIS:

-- 1.1) TOP 3 YOUNGEST PLAYERS (ATLEAST 5 GAMES PLAYED);
SELECT Player, Age, Played, Team, Pts as 'Points' FROM player_stats WHERE Played > 5
ORDER BY AGE LIMIT 3;

-- 1.2) TOP 3 OLDEST PLAYERS:
SELECT Player, Age, Played, Team, Pts as 'Points' FROM player_stats
ORDER BY AGE DESC LIMIT 3;

-- 1.3) AVERAGE AGE OF THE PLAYERS:
SELECT AVG(Age) FROM player_stats;

-- 1.4) AVERAGE AGE OF PLAYERS IN EACH TEAM:
SELECT Team, Avg(Age) FROM player_stats
GROUP BY Team;

-- 1.5) RELATIONSHIP BETWEEN AGE AND FIELD GOALS PER GAME;
SELECT Age, AVG(FG) FROM player_stats
GROUP BY Age
ORDER BY AVG(FG);

-- 1.6) COMPARE AGE OF EACH PLAYER & MAXIMUM AGE IN THE POSITION THEY ARE PLAYING; 
SELECT *, MAX(AGE) OVER(PARTITION BY POSITION) FROM player_stats;

-- 2) PERFORMANCE ANALYSIS;

-- 2.1) HIGHEST FIELD GOALS PER GAME:
SELECT Player, FG FROM player_stats
ORDER BY FG DESC LIMIT 1;

-- 2.2) PLAYERS WITH ZERO FIELD GOALS PER GAME:
SELECT Player, Team, FG FROM player_stats
WHERE FG = 0;

-- 2.3) RELATIONSHIP BETWEEN PLAYER'S AGE AND REBOUNDS PER GAME:
SELECT Age, AVG(ORB) AS 'OFFENSIVE REBOUNDS', AVG(DRB) AS 'DEFENSIVE REBOUNDS', (AVG(TRB)) AS 'TOTAL REBOUNDS' FROM player_stats
GROUP BY AGE
ORDER BY (AVG(TRB));

-- 2.4) RELATIONSHIP BETWEEN PLAYER'S AGE AND POINTS PER GAME:
SELECT Age, AVG(PTS) FROM player_stats
GROUP BY AGE
ORDER BY (AVG(PTS));

-- 2.5) PLAYERS WITH MOST 3 POINTERS PER GAME;
SELECT Player, 3P FROM player_stats
ORDER BY 3P DESC;

-- 2.6) PLAYERS WITH MOST POINTS PER GAME (AT LEAST 20 GAMES);
SELECT Player, Pts AS 'POINTS' FROM player_stats WHERE Played >= 20
ORDER BY Pts DESC;

-- 2.7) LIST OF PLAYERS WITH MAXIMUM NUMBER OF FIELD GOALS COMPARED WITH MAXIMUM FIELD GOALS SCORED BY A PLAYER FROM THEIR TEAM (AT LEAST 20 GAMES):
SELECT *, MAX(FG) OVER(PARTITION BY TEAM) AS 'MAX GOALS SCORED BY A PLAYER IN TEAM'  FROM player_stats WHERE played >=20;

-- 2.8) PLAYERS WITH LEAST POINTS PER GAME (AT LEAST 20 GAMES)
SELECT Player, Pts AS 'POINTS' FROM player_stats WHERE Played >= 20
ORDER BY Pts;

-- 2.9) PLAYERS WITH MOST BLOCKS PER GAME (AT LEAST 20 GAMES)
SELECT Player, BLK AS 'BLOCKS' FROM player_stats WHERE Played >= 20
ORDER BY BLK DESC;

-- 2.10) PLAYERS WITH LEAST BLOCKS PER GAME (AT LEAST 20 GAMES)
SELECT Player, BLK AS 'BLOCKS' FROM player_stats WHERE Played >= 20
ORDER BY BLK;

-- 3) TEAMS ANALYSIS;

-- 3.1) TEAMS WITH MOST PLAYERS;
SELECT Team, COUNT(Player) FROM player_stats
GROUP BY Team
ORDER BY COUNT(Player) Desc;

-- 3.2) TEAMS WITH HIGHEST POINTS PER GAME;
SELECT Team, SUM(PTS) FROM player_stats
GROUP BY Team
ORDER BY SUM(PTS) Desc;

-- 3.3) TEAMS WITH HIGHEST BLOCKS PER GAME;
SELECT Team, SUM(BLK) FROM player_stats
GROUP BY Team
ORDER BY SUM(BLK) DESC;

-- 3.4) TEAMS WITH HIGHEST 3 POINTER PER GAME;
SELECT Team, SUM(3P) FROM player_stats
GROUP BY Team
ORDER BY SUM(3P) DESC;

-- 3.5) TEAMS WITH LOWEST 3 POINTER PER GAME;
SELECT Team, SUM(3P) FROM player_stats
GROUP BY Team
ORDER BY SUM(3P);

-- 3.6) TEAM WITH HIGHEST REBOUNDS;
SELECT Team, SUM(TRB) FROM player_stats
GROUP BY Team
ORDER BY SUM(TRB) DESC;

-- 3.7) TEAMS WITH LOWEST REBOUNDS;
SELECT Team, SUM(TRB) FROM player_stats
GROUP BY Team
ORDER BY SUM(TRB);

-- 4) POSITION ANALYSIS:

-- 4.1) POSITIONS WITH HIGHEST POINTS:
SELECT position, SUM(Pts) FROM player_stats
GROUP BY position
ORDER BY SUM(Pts) DESC;

-- 4.2) POSITIONS WITH LEAST POINTS:
SELECT position, SUM(Pts) FROM player_stats
GROUP BY position
ORDER BY SUM(Pts);

-- 4.3) RANK TOP 3 PLAYERS IN A TEAM ACCORDING TO FIELD GOALS SCORED;
SELECT * FROM (SELECT *, row_number()  OVER(PARTITION BY Team ORDER BY FG) as RANKS FROM player_stats)X
WHERE X.RANKS < 4;

-- 4.4) POSITIONS WITH HIGHEST BLOCKAGES;
SELECT position, SUM(BLK) FROM player_stats
GROUP BY position
ORDER BY SUM(BLK) DESC;

-- 4.4) POSITIONS WITH LOWEST BLOCKAGES PER GAME:
SELECT position, SUM(BLK) FROM player_stats
GROUP BY position
ORDER BY SUM(BLK);

-- 4.5) RELATIONSHIP BETWEEN POSITION AND FIELD GOALS PER GAME:
SELECT position, AVG(FG) FROM player_stats
GROUP BY position
ORDER BY AVG(FG);

-- 4.6) RELATIONSHIP BETWEEN POSITION AND AGE:
SELECT Age, position, COUNT(position) FROM player_stats
GROUP BY Age, Position
ORDER BY COUNT(Position);













